"""empty message

Revision ID: 704fcf957f57
Revises: d081acce7b16
Create Date: 2023-01-31 10:50:40.716623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704fcf957f57'
down_revision = 'd081acce7b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('input', sa.String(length=2000), nullable=False))
    op.drop_column('messages', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message', sa.VARCHAR(length=2000), nullable=False))
    op.drop_column('messages', 'input')
    # ### end Alembic commands ###